### ISSUE TITLE
A blank string used for placeholder replacement can cause memory issue

### ISSUE THREAD

**Issue by pjbollinger** [betamaxpy/betamax#169]
**Version: betamax-0.8.0**

If you define a placeholder as described in the following, it can lead to memory issues, depending on how many blank strings you're trying to replace.

```python
username = ''
config.define_cassette_placeholder('<USERNAME>', username)
```

For example, if I have the original string `'WOW'` and perform the `.replace()` function, it will result in the following.
 ```python
>>> 'WOW'.replace('','<USERNAME>')
'<USERNAME>W<USERNAME>O<USERNAME>W<USERNAME>'
```

If you have multiple placeholders with a blank string, this compounds and can cause a memory issue. I experienced this issue in `src.betamax.cassette.interaction.py::Interaction::replace_in_uri`, but would think this is applicable to all functions that use `str.replace()` and it looks like it exists on the most current version of betamax too.

I can submit a PR to check for blank strings prior to calling `str.replace()`, but figure I'd bring it up in an issue first.

**Comment by hroncok** [comment]
Since emoji responses don't send notifications, I'm letting you know I like the idea to check for blank strings and refusing to continue.
