### ISSUE TITLE
Async and AioHTTP support?

### ISSUE THREAD

**Issue by PythonCoderAS** [betamaxpy/betamax#180]
Does Betamax support the AioHTTP sessions objects? If not, are there any plans to support it? If there's no current support I can fork Betamax and then change it to use async.

**Comment by sigmavirus24** [comment]
I'll quote the repository description to answer your question:

> A VCR imitation designed only for python-requests.

**Comment by PythonCoderAS** [comment]
Ahh. So I'll have to fork it.

**Comment by sigmavirus24** [comment]
Given how specific 99% of it this code is to requests, I would recommend starting from scratch
