### ISSUE TITLE
DeprecationWarning in decorators docstring

### ISSUE THREAD

**Issue by jayvdb** [betamaxpy/betamax#185]
```
/usr/lib/python3.8/site-packages/betamax/decorator.py:11: DeprecationWarning:

invalid escape sequence \*
```

Seems to be triggered by

`:param \*\*use_cassette_kwargs:`

The docstring could be changed to be r'..', but does that then break Sphinx?

**Comment by hroncok** [comment]
The docstring should be changed to be r'..', it doesn't break Sphinx.
