### ISSUE TITLE
Remove deprecated utcnow calls

### ISSUE THREAD

**Issue by sigmavirus24** [betamaxpy/betamax#209]
`datetime.datetime.utcnow()` is deprecated. We should use `datetime.datime.now(datetime.timezone.UTC)` where we use utcnow today

**Comment by cryptomail** [comment]
FYI: I think there are a few more deprecation spots 😿 
![Screenshot 2024-08-20 at 12 58 12 PM](https://github.com/user-attachments/assets/6f9c22e4-a15a-4a52-9667-11d04063bfe0)
adapter.py is an example I'm getting Python 3.12 complaints about.

**Comment by cryptomail** [comment]
oh wait, latest in source doesn't have this!
