### ISSUE TITLE
Migrate Issues to GitLab

### ISSUE THREAD

**Issue by sigmavirus24** [betamaxpy/betamax#30]
Use script to migrate issues from GitHub to [GitLab](https://gitlab.com/sigmavirus24/betamax)
##

**Comment by kragniz** [comment]
I'm guessing this isn't going to happen? If not, this should be closed.

**Comment by sigmavirus24** [comment]
Yeah, this project picked up steam over here and it'll be tough to move it to the Betamax group on GitLab.
